# Generated by Django 3.2.16 on 2025-04-18 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('reason', models.CharField(choices=[('vacation', 'Отпуск'), ('wedding', 'Свадьба'), ('hb', 'День рождения')], max_length=64, verbose_name='Причина сбора')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сбора')),
                ('goal_value', models.PositiveIntegerField(verbose_name='Сумма сбора')),
                ('current_value', models.IntegerField(default=0, verbose_name='Собрано средств')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collects/images/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало сбора')),
                ('finish_at', models.DateTimeField(verbose_name='Конец сбора')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сбор',
                'verbose_name_plural': 'сборы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('total', models.PositiveIntegerField(verbose_name='Сумма пожертвования')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='donations.collect', verbose_name='Сбор')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
            ],
            options={
                'verbose_name': 'Пожертвование',
                'verbose_name_plural': 'пожертвования',
                'ordering': ('-payment_date', '-total'),
                'default_related_name': 'payments',
            },
        ),
    ]
