# Generated by Django 3.2.16 on 2025-04-19 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_collect_current_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='goal_value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма сбора'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма пожертвования'),
        ),
    ]
